language: java
jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE surveys;" -U postgres
  - psql -c "CREATE USER survey WITH PASSWORD 'admin';" -U postgres


jobs:
  include:
    - stage: build App
      script: mvn clean install
    - stage: Test
      script: mvn clean test
