language: java
jdk:
  - openjdk8

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - psql -c "CREATE DATABASE surveys;" -U postgres
  - psql -c "CREATE USER survey WITH PASSWORD 'admin';" -U postgres


jobs:
  include:
    - stage: build app and test
      script: mvn clean install
