language: java

jdk:
  - openjdk8

services:
  - postgresql

env:
  - NODE_VERSION=13.1.0

install:
  - nvm install $NODE_VERSION
  - npm install
  - npm install -g ionic


branches:
  only:
    - master

before_script:
  - psql -c "CREATE DATABASE surveys;" -U postgres
  - psql -c "CREATE USER survey WITH PASSWORD 'admin';" -U postgres


jobs:
  include:
    - stage: build app and test
      script: mvn clean install
#    - stage: build ui
#      script:
#        - cd ui
#        - npm ci
#        - ionic build --prod -- --base-href ./
